spring.application.name=BatterySwap
# ===============================
# = DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/bsm_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# D�ng n�y kh�ng c?n thi?t, Spring Boot s? t? ??ng nh?n di?n t? URL
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =================================================
# C?U H�NH THYMELEAF (CHO FILE HTML)
# =================================================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
